module.exports = {
  REDDIT_USERNAME: 'heroesdiff',
  REDDIT_PASSWORD: 'heroesdiffer123',
  REDDIT_SUBREDDIT: 'heroesdiff',
  REDDIT_EMAIL_USELESS: 'heroesdiffer@gmail.com',
  REDDIT_CLIENT_ID: 'q3abVx8A8N7A8A',
  REDDIT_CLIENT_SECRET: 'wWg2WFWNHSUrcOo-aui3djaEoYs',
  REDDIT_USERAGENT: 'Heroes Differ 1.0 by /u/jamiephan',
  REDDIT_POST_TEMPLATE: __dirname + '/reddit-post.template',
  REDDIT_POST_TITLE_TEMPLATE: '[Test Post] Heroes Differ: v{{NewVersion}} <--> v{{OldVersion}}',
  GETT_EMAIL: 'heroesdiffer@gmail.com',
  GETT_PASSWORD: 'heroesdiffer123',
  GETT_APIKEY: 't0l8xtcrnuclrx4s6oypf9io1or59343j2m64em23f53ulje5ewmi',
  HEROES_OF_THE_STORM_INSTALLATION_PATH: '/mnt/d/Program Files/Heroes of the Storm/',
  SNAPSHOT_SAVE_PATH: __dirname + '/diff/',
  SNAPSHOT_SAVE_PREFIX: 'snapshot-',
  SNAPSHOT_SAVE_EXTENSIONS: ['xml', 'galaxy', 'txt', 'StormLayout'],
  DIFF_RESULTS_FILENAME_TEMPLATE: 'diff_{{NewBuild}}_{{OldBuild}}.txt',
  DIFF_RESULTS_SAVE_PATH: __dirname + '/diff_results/',
};
